## K Nearest Neighbour Classifier

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
from sklearn.datasets import make_classification

X,y = make_classification(
    n_samples = 1000,
    n_features= 3,
    n_redundant =1,
    n_classes =2, # binary target/label
    random_state =999

)

In [3]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [4]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,

In [5]:
X.shape,y.shape

((1000, 3), (1000,))

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.20,random_state =42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
classifiers = KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [9]:
classifiers.fit(X_train,y_train)

KNeighborsClassifier()

In [10]:
y_pred = classifiers.predict(X_test)

In [12]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0])

In [13]:
y_test

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0])

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [15]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[98 12]
 [ 5 85]]
0.915
              precision    recall  f1-score   support

           0       0.95      0.89      0.92       110
           1       0.88      0.94      0.91        90

    accuracy                           0.92       200
   macro avg       0.91      0.92      0.91       200
weighted avg       0.92      0.92      0.92       200



In [ ]:
# ## Task
# Gridsearchcv
# Randomsearchcv

## KNN Regressor

In [16]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=2, noise=10, random_state=42)

In [17]:
X

array([[-0.16711808,  0.14671369],
       [-0.02090159,  0.11732738],
       [ 0.15041891,  0.364961  ],
       ...,
       [ 0.30263547, -0.75427585],
       [ 0.38193545,  0.43004165],
       [ 0.07736831, -0.8612842 ]])

In [18]:
y

array([-1.49969499e+01, -1.26780889e+01,  1.77754545e+01,  6.66146467e+00,
       -1.41955300e+01, -2.52448482e+01, -3.92316263e+01, -5.20180382e+01,
        5.76368853e+00, -5.01186029e+01,  3.68932300e+01, -5.73879093e+01,
       -1.43015904e+01, -3.14639243e+01,  3.73110627e+01,  1.56178696e+01,
       -6.66080007e+00, -4.89229382e+01, -9.58772599e+00,  8.53715394e+01,
        1.66537460e+01, -3.41293946e+01, -3.72378063e+01, -4.87281315e+01,
       -5.51790322e+01, -3.55366169e+01, -3.72747912e+00,  7.34218222e+01,
        1.01718119e+02, -1.90116475e+01, -3.43901341e+01, -9.62943086e+00,
        1.16658030e+01,  2.08905862e+01, -1.70900105e+01, -1.50447947e+01,
        4.68228521e+01, -1.89552845e+01,  5.71898896e+01, -5.48067724e+01,
       -5.16310769e+01, -8.08939793e+00,  6.06663511e+01,  3.55254095e+01,
        1.04233163e+01, -4.30586696e+01,  1.12998389e+00,  2.31342762e+01,
       -6.13582958e+00,  2.60353115e+01,  5.87540393e+01,  2.13374470e+01,
       -4.73477124e+01,  

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [21]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((670, 2), (330, 2), (670,), (330,))

In [22]:
from sklearn.neighbors import KNeighborsRegressor

In [23]:
regressor = KNeighborsRegressor(n_neighbors=6, algorithm='auto')
regressor.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=6)

In [24]:
y_pred = regressor.predict(X_test)

In [26]:
y_pred

array([ 44.28436588,  -8.83610851, -18.33906448, -13.36468289,
        36.4901953 ,  15.59754172,  62.47359613, -30.6064089 ,
       -69.62828115, -10.37525416,  21.80810748,  -6.38215514,
       -69.82924403,  58.86216428,  14.91021342,   1.81128438,
       -58.89280399,  23.40509015, -23.98759248,  26.42054164,
        20.79753432,  14.87340636, -23.39345711, -42.50851757,
       -43.40835337,  23.13574661, -57.12971023,  57.41364484,
       -18.90795489,  78.268256  , -76.76262901,  26.79530007,
       -55.89232411,  -6.77954881, -50.48642122,  -5.7568218 ,
        19.08611482,  33.72772173,  13.0168595 , -47.24565041,
        81.93720521,  29.84752288,  39.13279368, -70.67275387,
        19.13441662,  24.14349076, -31.86088325,  -8.79922574,
        62.64114459,  65.54226395,  59.37221042,  75.39213118,
       -59.7684246 , -30.04634947, -47.24565041, -24.36754183,
       -33.29603737,  33.50360127,  90.10067475,  33.82278541,
        37.59356966,   2.09414764, -23.96311167,  -3.29

In [27]:
y_test

array([ 33.91180896,  -1.97979693, -33.91986709, -25.57751852,
        41.12484462,  22.86165584,  62.04490806, -35.11001752,
       -81.78946988,  -0.61858456,  37.22384582, -13.47709505,
       -58.33323621,  63.25368061,   8.91589013,  -0.55106221,
       -62.83504876,  19.78135865, -19.13467085,  25.95149338,
        25.10269203,  17.8807435 ,  -4.24331075, -41.81910717,
       -35.75365733,  19.80731004, -42.76244682,  62.50504626,
       -19.19132574,  65.51648058, -78.51835075,  50.1778718 ,
       -80.78992883,  -1.1824125 , -42.04048277, -17.35762181,
         1.00096454,  29.56751145,  -8.68010834, -55.34006845,
       109.29769144,  41.06753031,  32.66711134, -64.55847412,
        30.314414  ,  37.35520487, -44.41453468,  -2.40313934,
        49.97758634,  71.48954025,  62.54974165,  90.5992387 ,
       -53.91553003, -42.69734026, -48.72813148, -34.39013412,
       -51.68191933,  36.89322999, 100.36345612,  37.1210935 ,
        34.9205836 ,  -2.53184829, -19.08554869,  -4.55

In [31]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [32]:
print(r2_score(y_pred,y_test))
print(mean_absolute_error(y_pred,y_test))
print(mean_squared_error(y_pred,y_test))
print(root_mean_squared_error(y_pred,y_test))

0.9084261379357146
9.009462452972217
127.45860414317289
11.289756602476995
