In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4]

In [3]:
np.array(l1)

array([1, 2, 3, 4])

In [14]:
l2=list(range(1,13))

In [15]:
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [16]:
a=np.array(l2)

In [17]:
a.shape,a.ndim,a.size

((12,), 1, 12)

In [19]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
a1=np.random.randint(1,9,size=(3,2))
a1

array([[4, 6],
       [5, 1],
       [3, 4]], dtype=int32)

In [38]:
a1.shape, a1.size, a1.ndim

((3, 2), 6, 2)

In [31]:
a2=np.random.randint(1,9,size=(3,3))
a2

array([[8, 4, 4],
       [8, 4, 3],
       [6, 3, 3]], dtype=int32)

In [30]:
a2.shape, a2.size, a2.ndim

((3, 3), 9, 2)

In [33]:
a1+a2

array([[14, 12,  5],
       [13, 10,  5],
       [ 8,  6,  7]], dtype=int32)

In [34]:
a1*a2

array([[48, 32,  4],
       [40, 24,  6],
       [12,  9, 12]], dtype=int32)

In [35]:
a1/a2

array([[0.75      , 2.        , 0.25      ],
       [0.625     , 1.5       , 0.66666667],
       [0.33333333, 1.        , 1.33333333]])

In [39]:
a1

array([[4, 6],
       [5, 1],
       [3, 4]], dtype=int32)

In [40]:
a1.shape, a2.shape

((3, 2), (3, 3))

In [41]:
a1+a2

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [44]:
a1.dot(a2.T)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [46]:
b1=a1.T

In [47]:
b1.shape

(2, 3)

In [48]:
b1.dot(a2)

array([[90, 45, 40],
       [80, 40, 39]], dtype=int32)

In [50]:
a2.dot(a1)

array([[64, 68],
       [61, 64],
       [48, 51]], dtype=int32)

In [51]:
a1.max()

np.int32(6)

In [52]:
a1.min()

np.int32(1)

In [53]:
a1.sum()

np.int64(23)

In [54]:
a1.mean()

np.float64(3.8333333333333335)

In [55]:
a1

array([[4, 6],
       [5, 1],
       [3, 4]], dtype=int32)

In [56]:
a1.max(axis=0)

array([5, 6], dtype=int32)

In [57]:
a1.max(axis=1)

array([6, 5, 4], dtype=int32)

In [58]:
a3=np.array([[[1,2],[3,4]]])

In [59]:
a3

array([[[1, 2],
        [3, 4]]])

In [60]:
a3.shape, a3.ndim, a3.size

((1, 2, 2), 3, 4)

In [62]:
a4=np.ones((4,3,2))

In [63]:
a4

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [64]:
a4.ndim, a4.size , a4.shape

(3, 24, (4, 3, 2))

In [66]:
a2

array([[8, 4, 4],
       [8, 4, 3],
       [6, 3, 3]], dtype=int32)

In [67]:
a2[2,0]

np.int32(6)

In [70]:
a2[1:3,1:3]

array([[4, 3],
       [3, 3]], dtype=int32)