In [1]:
import numpy as np

In [2]:
l = list(range(10))

In [3]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
a=np.array(l)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a.size

10

In [10]:
a.shape

(10,)

In [11]:
np.array(19)

array(19)

In [12]:
a.max()

np.int64(9)

In [13]:
a.min()

np.int64(0)

In [14]:
a.sum()

np.int64(45)

In [15]:
a.mean()

np.float64(4.5)

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b=np.array([1,2,3,4],dtype=float)

In [24]:
b

array([1., 2., 3., 4.])

In [21]:
b.dtype

dtype('float64')

In [22]:
a.dtype

dtype('int64')

In [26]:
c=b.astype(int)

In [25]:
b.dtype

dtype('float64')

In [27]:
c.dtype

dtype('int64')

In [28]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a*2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a-6

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3])

In [32]:
a/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [33]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b= np.ones(10)

In [35]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
a+b.astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
c= np.random.randint(1,10,(2,2))

In [48]:
c.shape

(2, 2)

In [49]:
c.ndim

2

In [50]:
c

array([[9, 9],
       [3, 4]], dtype=int32)

In [57]:
d= np.arange(10,20,1)

In [58]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.shape, d.shape,a.ndim, d.ndim

((10,), (10,), 1, 1)

In [63]:
a+d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [64]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
aa=a.reshape(5,2)

In [71]:
aa.ndim

2

In [72]:
aa.shape

(5, 2)

In [73]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
d[5]

np.int64(15)

In [76]:
d[4:7]

array([14, 15, 16])

In [77]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [82]:
a[2][1]

np.int64(5)

In [84]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [85]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [87]:
np.full((3,5),4.5)

array([[4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5]])

In [88]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [93]:
np.random.random((3,5))

array([[0.20776679, 0.57076191, 0.03756598, 0.89522426, 0.5925633 ],
       [0.12354632, 0.33952093, 0.60216058, 0.0694309 , 0.77019016],
       [0.53537869, 0.4158256 , 0.38228344, 0.84575009, 0.00344402]])

In [95]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [97]:
np.random.randint(0,10,(5,5))

array([[7, 5, 8, 5, 0],
       [9, 2, 2, 1, 8],
       [1, 5, 3, 3, 0],
       [3, 8, 9, 0, 4],
       [7, 4, 3, 8, 2]], dtype=int32)